const { withAppBuildGradle, withGradleProperties } = require('expo/config-plugins');
const fs = require('fs');
const path = require('path');

/**
 * Injects a release signingConfig into android/app/build.gradle using a local,
 * gitignored keystore (credentials/android/release.jks + release-credentials.json).
 * Needed because native folders are regenerated by `expo prebuild` and are not
 * committed, so the signing config has to be re-applied on every prebuild.
 *
 * Also bumps the Gradle daemon heap/metaspace — the default 2048m/512m runs into
 * Metaspace pressure building a release AAB across 4 ABIs on this project.
 */
module.exports = function withAndroidReleaseSigning(config) {
  config = withGradleProperties(config, (config) => {
    const jvmArgsProp = config.modResults.find(
      (item) => item.type === 'property' && item.key === 'org.gradle.jvmargs'
    );
    if (jvmArgsProp) {
      jvmArgsProp.value = '-Xmx4096m -XX:MaxMetaspaceSize=1024m';
    }
    return config;
  });

  return withAppBuildGradle(config, (config) => {
    const credentialsDir = path.join(__dirname, '..', 'credentials', 'android');
    const credentialsPath = path.join(credentialsDir, 'release-credentials.json');

    if (!fs.existsSync(credentialsPath)) {
      console.warn(
        '[withAndroidReleaseSigning] credentials/android/release-credentials.json not found — release builds will fall back to debug signing.'
      );
      return config;
    }

    const creds = JSON.parse(fs.readFileSync(credentialsPath, 'utf8'));
    const keystorePath = path.join(credentialsDir, creds.storeFile);

    let contents = config.modResults.contents;

    const releaseSigningBlock = `        release {
            storeFile file('${keystorePath}')
            storePassword '${creds.storePassword}'
            keyAlias '${creds.keyAlias}'
            keyPassword '${creds.keyPassword}'
        }
`;

    if (!contents.includes('signingConfigs.release')) {
      contents = contents.replace(
        /(signingConfigs\s*\{\n)/,
        `$1${releaseSigningBlock}`
      );

      contents = contents.replace(
        /(release\s*\{\n\s*\/\/ Caution![\s\S]*?)signingConfig signingConfigs\.debug/,
        `$1signingConfig signingConfigs.release`
      );
    }

    config.modResults.contents = contents;
    return config;
  });
};
